export const surpriseMePrompts = [
  'rank, artwork, sunset, containing deductive arguments valid premises conclusion, glass',
  'pixar style, scarlett leithold dressed in a bioluminescent dress, glowing eighties vibe, anthropomorphic, beautiful lighting, volumetrics, landscape, by Frank Chi and Sean Thurlow and Atey Ghailan',
  'Lazy day home',
  'Bioluminescent Portrait by James C. Christensen',
  'ethereal Bohemian Waxwing bird, Bombycilla garrulus :: intricate details, ornate, detailed illustration, octane render :: Johanna Rupprecht style, William Morris style :: trending on artstation --ar 9:16',
  "a minimalist contemporary cafe with a large round zen window view of a starry nebula, interior environment design, contempoary furniture, candlelight, 8k, octane render, arch viz, modern, space opera, ray traced, medium format",
  'beautiful koi fish inside glass of water, photo realistic, fine details, unreal engine',
  'space suit with boots, futuristic, character design, cinematic lightning, epic fantasy, hyper realistic, detail 8k --ar 9:16',
  'Western Cowboy riding his horse at night under the milky way galaxy, desert, HDR, anime scene',
  'face of a model closeup, Madison Beer, headshot, long beautiful flowing ink like hair, smoky makeup, shining eyes, grey-gold-blue eyes, gold flecks, defined eyes, realistic eyes, doe eyes, beautiful perfect symmetrical face, extremely detailed, melancholy expression, painted by Tom Bagshaw and Eve Ventrue and Jeremy Lipking, ultra hd, hdr, 8k, cinematic, dramatic lighting, studio Portrait Lighting, illuminated face, 85mm, volumetric lighting, ray tracing reflections',
  'gorgeous woman, peaceful, innocent, tranquil, long flowing hair, liquid rococo fractal, James Jean, Rutkowski, fluid acrylic, elegant gradients, intricate, octane render, depth, Kaluta, detailed eyes, incredibly detailed, hyperrealistic, pastel colours, Artgerm, WLOP, Rutkowski, fractal, 8k octane',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'bioluminescent ethereal water elementals nesting in a rock pool',
  'Nordic fjord, summer morning light, aerial view, cinematic Light, Soft illumination, cinematic composition, wide-angle, atmospheric,matte painting, Trending on artstation,',
  'Closeup of A weathered Lighthouse, A massive splash, an explosion of water, a violent sea, lightning, dramatic lighting, stormy environment',
  'James Christensen, style, portrait of a snow goddess, exquisite detail, 30-megapixel, 4k, 85-mm-lens, sharp-focus, intricately-detailed, long exposure time, f/8, ISO 100, shutter-speed 1/125, diffuse-back-lighting, award-winning photograph, facing-camera, looking-into-camera, monovisions, elle, small-catchlight, low-contrast, High-sharpness, facial-symmetry, depth-of-field, golden-hour, ultra-detailed photography, shiny metal surface with intricate swirling mother of pearl inlays, raytraced, global illumination',
  'Nordic fjord, summer morning light, aerial view, cinematic Light, Soft illumination, cinematic composition, wide-angle, atmospheric,matte painting, Trending on artstation',
  'intricate enormous hourglass time turner where a woman sits upon the sand fighting against the unstoppable flow of time, photorealistic, cinematic lighting',
  'airy, pin-up, sci-fi, steam punk, very deitaled, realistic, figurative painter, fineart, Oil painting on canvas, beautiful painting by Daniel F Gerhartz',
  'tumbling into singularity + beatiful anime spacegirl + blackhole, concept art, artstation, ultradetailed, 4k, 8k, hdr, hyperrealistic, octane render, unreal engine',
  'pixar style, scarlett leithold dressed in a bioluminescent dress, glowing eighties vibe, anthropomorphic, beautiful lighting, volumetrics, landscape, by Frank Chi and Sean Thurlow and Atey Ghailan',
  'abandoned car wreck without lamps, in the middle of a dark forest with moss. Extremely sharp, unreal engine',
  'resting in the mountains, beautiful blue sky, heavy detail',
  'Sci-fi comedy laboratory that 3d prints octopuses in pools of resin, Westworld, Cinematic, Color Grading, Editorial Photography, Photography, Photoshoot, Shot on 70mm lense, Depth of Field, DOF, Tilt Blur, Shutter Speed 1/1000, F/22, White Balance, 32k, Super-Resolution, Megapixel, ProPhoto RGB, VR, Lonely, Good, Massive, Natural Lighting, Incandescent, Optical Fiber, Moody Lighting, Cinematic Lighting, Studio Lighting, Soft Lighting, Volumetric, Contre-Jour, Beautiful Lighting, Accent Lighting, Global Illumination, Screen Space Global Illumination, Ray Tracing Global Illumination, Optics, Scattering, Glowing, Shadows, Rough, Shimmering, Ray Tracing Reflections, Lumen Reflections, Screen Space Reflections, Diffraction Grading, Chromatic Aberration, GB Displacement, Scan Lines, Ray Traced, Ray Tracing Ambient Occlusion, Anti-Aliasing, FKAA, TXAA, RTX, SSAO, Shaders, OpenGL-Shaders, GLSL-Shaders, Post Processing, Post-Production, Cel Shading, Tone Mapping, CGI, VFX, SFX, insanely detailed and intricate, hypermaximalist, hyper realistic, super detailed',
  'the prankster god Tanuki, forest background, by Naomi Okubo, Iwona Lifsches',
  'rain forst cove with waterfalls, beautiful lighting, volumetrics, landscape, bioluminescent by Frank Chi and Sean Thurlow and Atey Ghailan',
  'a photo of cat flying out to space as an astronaut, digital art',
  'a belgian astrounaut lost in space , 4k, hyperealistic, ray tracing',
  'a belgian astrounaut lost in space full body, 4k, hyperealistic, ray tracing, full image',
  'flying bengal cat on fire, playing with catnip and a mouse in space',
  'ice eagle fighting against a fire hawk on a iced and scorched place',
  'A female muslim biologist pet a cat on the moon which have big fire',
  'albino girl, curly, warrior, female, cyberpunk, robot, wings, assassin, raining, background',
  'a quasar forms at the end of a long hallway + liminal space + hyperrealistic + unreal engine',
  'a little girl with light brown short wavy curly hair and blue eyes floating in space, gazing in wonder at a quasar, Clear, detailed face. Clean Cel shaded vector art by lois van baarle, artgerm, Helen huang, by makoto shinkai and ilya kuvshinov, rossdraws, illustration',
  'sci-fi cosmic diarama of a quasar and jellyfish in a resin cube, volumetric lighting, high resolution, hdr, sharpen, Photorealism',
  'curved building facade made from transparent smooth and endless fluidity style parametric future architecture, concept art, highly detailed, beautiful scenery, cinematic, beautiful light, hyperreal, octane render, hdr, long exposure, 8K, realistic, fog, moody, gopro',
  'a moody foggy environment inside a curvilinear space looking up at a tall open oculus with light filtering down, back-lit uplit, unreal engine',
  ' a cover photography, body and face photo, a beautiful young woman covered in water and liquid, clothes old and ragged, half buried on trash and garbage, hyper realistic, model photography, 500px poses, detailed, intricate',
  'albino girl wrapped in kelp algae seaweeds in a white minimalist room, theatrical lighting',
  'happy marshmallows, in style of adventure time, intricate detail, concept art',
  'Hyper real glass flowers, blue organic twisting. octane render, unreal engine, blender render, immersive detail, enhanced quality',
  'Shells washed up on the beach、glitter、cinematic lighting,Unreal Engine、hyper quality、 soft studio lighting, octane render, hyper detailed, volumetric lighting, global illumination, detailed and intricate environment, 8k',
  'intricate knitted running shoe, product photography, octane, volumetric lighting –v 4',
  'Beautiful Impressionist painting of a dark dramatic character, Fusion between Jeremy Mann and Marta Dahlig and Daniel F Gerhartz, Annie Leibovitz, Long shot –v 4',
  'photo of a gorgeous blonde succubuss attractive in light gold and white intricate metallic armor revealing hot attractive body , desire, celestial palace hyperdetailed hyperrealistic –v 4',
  'Firefly bacteria ghostly glow armour spacesuit on the surface of Europa',
  'Walking the cobblestone road of an ancient Dieselpunk jungle village, vibrant, lovely, Anime scenery, Cell shaded, Fantasy, River, steps, Stylized, Cottagecore, Villagecore, Volumetric lighting, Beautiful lighting, Intricate detail, Chiaroscuro',
  'ghostpunk',
  'Astroid crashing into Earth',
  ' lion face made from most complex unimaginable spirals with unimaginable fractals universe made from exploding ethereal glass quantum particles voxels in infinity dimensions covered by complex sacred geometry, textured abstract',
  'dragon woman brown skin asian eyes silver scales, high detail',
  'A world destroyed by lightning falling into a black hole',
  'celestial space, nebulas, flyable humanoid, glance through the visor, seconds away from portal –ar 16:9 –test –creative –upbeta',
  'a tree of life on a floating island in cosmos, super realistic , 8k, insanely detailed, cinematic lighting',
  'existance, 4k, ultra realistic, -- ar 16:9',
  'an astronaut at the edge of space, existance, 4k, ultra realistic, -- ar 16:9',
  'an astronaut meet god at the deep space, ultra realistic',
  'crossing absolute horizon, black hole, interdimensional entity emerging from inside, photo realistic, 1920x1080, 16:9',
  'decidious trees in fall in dense fog and a fox with a bushy tail with stars shining as a witch rides across the moon',
  'deep space and astrounaut',
  'portrait of a woman, light streaming on her face while she poses in the darkness, chiaroscuro, photography',
  'portrait of a mermaid, sunlight streaming on her face while she poses in the darkness, chiaroscuro, photography',
  'an astronaut with apple logo eating dinner, cinematic, restaurant, 300DPI, sunset, mountain, edward hopper style',
  'ultra sharp award wining underwater nature photography of a woman riding a glistening gradient 🦄 sea horse, backlit, depth of field, ocean floor, lush vegetation, particles, solar rays, coral, golden fishes',
  'portrait of gothic snow white, sunlight streaming on her face while she poses in the darkness, chiaroscuro, photography',
  'portrait of snow white, sunlight streaming on her face while she poses in the darkness, chiaroscuro, photography',
  'a large droideka robot firing lasers with a sphere shield around it, sand and clay buildings setting, epic sci-fi, cinematic lighting , action scene',
  'baby astronaut with sad expression left alone on the moons surface, space, very small spaceship, footprints, perspective, hyper-realistic, ultra detailed, ultra sharp, hard contrast, 8K, 16mm lens'
  'wide angle full body in frame photo of a gorgeous beautiful girl Amouranth blue short messy glowing ice crystal hair standing model pose ice wings wearing tight fitting blue ice crystal long formal gown with intricate glowing blue lace detail blue sheer thigh high white lace nylons octane render artstation',
  'Busy street on machine planet, with machine creatures and THE GIANT robots, wide shot, detailed, intricate, hard focus, art by Myasoedov, Alphonse Mucha, Craig Mullins and Repin',
]
